spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_db
    username: developer
    password: Developer@
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: angelofag3095@gmail.com
    password: pernbzjqzejyhtbb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  logging:
    level:
      root: INFO
    output:
      ansi:
        enabled: ALWAYS

  jackson:
     serialization:
      fail_on_empty_beans: false
